MicrosoftDocs/azure-docs-sdk-node

docs-ref-conceptual/index.yml

Added a new section to the landing page using a "markdown" section type, in order to add a video. In the future, we'll want to remove the iframe and convert this to Markdown instead of HTML. Unfortunately, we couldn't do that today because the landing page pipeline doesn't support any of our docs-specific Markdown extensions ;( Once that is resolved, we can fix this.

Add "Start Here" section with video content

---

docs-ref-conceptual/node-azure-tools.md
docs-ref-conceptual/toc.yml

This change points Node developers toward Linux by default rather than windows

Update Quickstarts Web Apps link to use the Linux article

---

docs-ref-conceptual/index.yml

We may replace it with a new version soon, but this just pulls the old one down for the time being.
Request review from @rloutlaw  /cc: @johnpapa

Remove "get started" video from dev center home

---

README.md
bread/toc.yml
docs-ref-conceptual/index.yml
docs-ref-conceptual/toc.yml

Initial work on refresh of JavaScript and Node.js Dev Center docs.
**Changes:**
- Rename to "Azure for JavaScript & Node.js developers"
- Refresh of hosting types
- Cleaned up Debugging section

Refresh of JavaScript and Node.js Dev Center docs

---

docs-ref-conceptual/index.yml

This updates the link to the Azure Remote Debugging docs, as the feature is no longer in preview.

Update link to Azure Remote Debugging docs

---

docs-ref-mapping/reference.yml

This is to go along with the fact that `@azure/azure-servicebus` and `@azure/azure-eventhubs` both were dropped from the CI. Robert Outlook fixed this. 
This is just correcting the landing location of one of those two GA packages.

Placing arm-servicebus into the management Section of the ToC

---

docs-ref-mapping/reference.yml

Addressing issue in reference.yml that prevents the sidebar for the speech-service.md from rendering.
* Removed: `landingPageType`, left `href`

Addressing issue in reference.yml for Speech service

---

.openpublishing.publish.config.json
docfx.json

Update docfx.json, update the monikers. End goal is that the moniker `azure-node-legacy` correctly renders.

Fix Legacy Moniker Build

---

docs-ref-services/keyvault-keys-readme.md

Hi hi! I wonder where else this could have slipped through! 🙏 any help appreciated.
The sign example in the PR changes uses RS256, which expects a message of at least 32 bytes. This sample exists in a section called "Sign Data", so seems like the correct solution is to switch to the `signData` method, which doesn't have this limitation.
Spotted on the customer issue: https://github.com/Azure/azure-sdk-for-js/issues/12654
If everything is ok and this ends up merged:
Fixes https://github.com/Azure/azure-sdk-for-js/issues/12654

[Key Vault Keys] Using signData in the Sign Data section

---

docs-ref-services/event-hub.md

The client package wasn't in the documentation here but really should have been as it's 
the most commonly used package.

Adding instructions for event-hubs client package

---

docs-ref-services/latest/key-vault-index.md

The page https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/c67e75cb905ec431387183157a82ca96fbedfa80/docs-ref-services/latest/key-vault-index.md powers the content in https://docs.microsoft.com/en-us/javascript/api/overview/azure/key-vault-index?view=azure-node-latest
This PR updates it to match with what is in the azure-sdk-for-js repo for Key Vault i.e. https://github.com/azure/azure-sdk-for-js/blob/master/sdk/keyvault/README.md

Update Key Vault service level readme

---

docs-ref-services/latest/event-hub.md

The page https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/c67e75cb905ec431387183157a82ca96fbedfa80/docs-ref-services/latest/event-hub.md powers the content in https://docs.microsoft.com/en-us/javascript/api/overview/azure/event-hub?view=azure-node-latest
This PR updates it to match with what is in the azure-sdk-for-js repo for Event Hubs i.e. https://github.com/azure/azure-sdk-for-js/blob/master/sdk/eventhub/README.md

Update Event Hubs service level readme

---

docs-ref-services/latest/service-bus.md

The page https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/c67e75cb905ec431387183157a82ca96fbedfa80/docs-ref-services/latest/service-bus.md powers the content in https://docs.microsoft.com/en-us/javascript/api/overview/azure/service-bus?view=azure-node-latest
This PR updates it to match with what is in the azure-sdk-for-js repo for Service Bus i.e. https://github.com/azure/azure-sdk-for-js/blob/master/sdk/servicebus/README.md and follow the guidelines to add pointers to older package versions

Update Service Bus service level readme

---

docs-ref-services/latest/storage-overview.md

`azure-arm-storage` has been deprecated in favor of `@azure/arm-storage`. This PR updates the landing page for Storage in API reference docs to not refer to the old package anymore. It was a miss from the last time it was updated

Remove example for older package azure-arm-storage

---

ci-configs/packages-legacy.json

Testing to see if adding an entry to packages-legacy file is enough to make the ref docs appear in the legacy moniker
cc @scbedd, @danieljurek

Add azure-arm-eventhub to packages-legacy

---

docs-ref-services/latest/eventgrid.md

The landing page for services are meant to follow a template listing all applicable packages, their API References and samples.
This PR does the above except the samples part which we can add for the new version once it goes GA

Update the landing page for Event Grid

---

ci-configs/packages-legacy.json

Now that we've released @azure/eventgrid@4.0.0, move the older version
to the legacy monikor. This will allow us to continue to link to the older
API docs from our ToC.

Generate docs for @azure/eventgrid@2.0.0 in legacy moniker

---

docs-ref-mapping/reference-unified.yml

Trying to make the communication identity and phone numbers ref docs show up. Related to https://github.com/Azure/azure-sdk-for-js/issues/14457

Add Communication Identity and Phone Numbers pkgs

---

ci-configs/packages-preview.json

These duplicates were added by older versions of onboarding automation. This PR removes them. While they don't break the build duplicates in the onboarding file may show up as multiple entries for the same package in the ToC. 
Also, before merging, I'll need to know what to do with `@azure/opentelemetry-exporter-azure-monitor`

Remove detected duplicates

---

docs-ref-services/latest/eventgrid.md

As part of https://github.com/Azure/azure-sdk-for-js/issues/15315 the API ref docs for azure-eventgrid was brought back, but with a different url. This PR updates the Event Grid landing page with the new URL
cc @danieljurek, @ellismg

Fix link for legacy eventgrid package

---

docs-ref-mapping/reference-unified.yml
docs-ref-mapping/reference.yml

Removing the "Core" node from the TOC as per discussions in https://github.com/Azure/azure-sdk-for-js/issues/15905 as it does not correspond to any Azure service like the other nodes. Packages under it should start appearing under "Other"

Remove the Core node

---

docs-ref-services/latest/mysql.md

ssl: true in mysql.createConnection() leads to unexpected behaviour. ssl option takes an object value pointing to a ca-cert filename.

Update SSL option

---

docfx.json

Metadata cleanup for the following ms.service values:
- cdn replaced with azure-cdn
- app-service-logic replaced with logic-apps
- log-analytics replaced with azure-monitor and ms.subservice = logs
- search replaced with cognitive-search
- application-insights replaced with azure-monitor and ms-subservice = application-insights
visual-studio-online was not retagged.
For details about this work, see [User story 774326](https://ceapex.visualstudio.com/CPS/_workitems/edit/774326)

Metadata retagging - User story 774326

---

metadata/latest/azure-functions.json
metadata/legacy/azure-functions.json
metadata/legacy/durable-functions.json

We [recently GA'ed](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-functions-node-js-v4-programming-model-is-generally/ba-p/3929217) new major versions of both functions packages.
cc @hossam-nasr

Update Azure Functions metadata files to new major versions

---

docsms-allowlist/js-allowlist.txt

The azure-sdk team has an [automated pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5213&_a=summary) which merges main->live every Wednesday at 4am PDT. Each repository has a <lang>-allowlist.txt file which includes patterns that are safe to merge. docfx.json is not in this list, mainly because there were two live site incidents related to changes to docfx.json. Recently, the pipelines have blocked merges because of changes to docfx.json which have been coming from other automated Learn sources. @nickwalkmsft and I chatted and decided to relax the restriction and allow changes to docfx.json to be merged.
This same change is being made to the following docs repositories:
- Azure/azure-docs-sdk-dotnet
- Azure/azure-docs-sdk-java
- MicrosoftDocs/azure-docs-sdk-node
- …

Add docfx.json to the allow list for automatic merging from main->live

---

docsms-allowlist/js-allowlist.txt

My preview PR updated the allow list and that change failed the auto-merge. The allow list isn't a file that's often updated and, even then, is only updated by hand, not automation. Don't prevent the auto-merge from main->live for allow list changes.

Add docsms-allowlist directory to allow list for the repository

---

docfx.json

Fixes: https://github.com/Azure/azure-sdk-for-js/issues/26493

Remove -index.md files from publishing (reduces OPS publishing errors)
