- docfx.json
This is ready for merge. Awaiting review by @TomArcher and/or @erickson-doug
> change header to azure header

- appveyor.yml
- docs-ref-conceptual/index.md
> Fixes Azure header and a few other merges

- docs-ref-services/appservice.md
> updated code snippet

- docs-ref-conceptual/includes/appservice-samples.md
API Sample should not be included until the README.md exists, minimally
#sign-off as per @TomArcher
> removed API sample as it has no readme

- docs-ref-conceptual/includes/appservice-samples.md
https://azure.microsoft.com/en-us/resources/samples/meanjs/
> added new code sample link

- docs-ref-services/redis-cache.md
Bad file formatting (my fault). Fixed.
> Update file formatting

- docs-ref-conceptual/includes/appservice-samples.md
request #sign-off as per @TomArcher
> adding back food truck, assuming readme changes are merged

- docs-ref-services/cdn.md
Correcting https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/38
Request #sign-off as per @TomArcher
> Update cdn.md Example Code

- docs-ref-services/notification-hubs.md
Request #sign-off as per @TomArcher
> Update notification-hubs.md Samples Links

- docs-ref-services/notification-hubs.md
> Update notification-hubs.md JS Code Example

- docs-ref-services/cognitive-services.md
Correcting #41 
Request #sign-off as per @TomArcher
> Update js example in cognitive-services.md

- docs-ref-services/cosmos-db.md
Corrects #39 and #40 
Request #sign-off as per @TomArcher
> Update cosmos-db.md Example code and Samples

- docs-ref-services/key-vault.md
> added example for key vault

- docs-ref-services/advisor.md
Add code example for Advisor
#sign-off as per @TomArcher
> Advisor - Refactored the code snippet

- docs-ref-services/authorization.md
Updated code example for management section
#sign-off as per @TomArcher
> Node - Authorization - Updated code snippet

- docs-ref-services/postgresql.md
> Change 'module' to 'package' in headers

- docs-ref-services/appservice.md
> code formatting and typo

- docs-ref-services/search.md
no samples exist for this
#sign-off @TomArcher
> new code example and formatting

- docs-ref-services/notification-hubs.md
* Changing code example to be consistent style with other updated code examples. 
* Updating to the consistent style for displaying Samples links in bulleted list format instead of a table.
> Update formatting in notification-hubs.md

- docs-ref-services/cosmos-db.md
* Changing code example to be consistent style with other updated code examples. 
* Updating to the consistent style for displaying Samples links in bulleted list format instead of a table.
> Update formatting in cosmos-db.md

- docs-ref-services/cognitive-services.md
* Changing code example to be consistent style with other updated code examples. 
#sign-off
> Update formatting in cognitive-services.md

- docs-ref-services/cdn.md
* Changing code example to be consistent style with other updated code examples. 
* Updating to the consistent style for displaying Samples links in bulleted list format instead of a table.
#sign-off
> Update formatting in cdn.md

- docs-ref-services/analysis-services.md
> Update formatting and example code in analysis-services.md

- docs-ref-services/media-services.md
> Update formatting and example code in media-services.md

- docs-ref-services/machine-learning.md
Updated management code sample
#sign-off as per @TomArcher
> Azure - Node - Machine Learning modules

- docs-ref-services/iot-hub.md
> added IoT examples

- docs-ref-conceptual/includes/mysql-samples.md
Update links to more relevant examples. Use bullet points formatting.
> Update sample links

- docs-ref-services/mysql.md
Update example with ES6 syntax.
> Update MySQL Docs

- docs-ref-services/monitor.md
> Azure Monitor - Updated example code

- docs-ref-conceptual/node-sdk-azure-authenticate-principal.md
> Azure Service Principle - Fix Spelling

- docs-ref-services/site-recovery.md
> Azure Site Recovery - Updated example code

- docs-ref-services/advisor.md
Added missing intro sentences and fixed heading levels
Needs review and then @sign-off
> Advisor - intros and headings

- docs-ref-services/analysis-services.md
> Analysis Server - add intros

- docs-ref-services/cosmos-db.md
> Cosmos DB - intros and headings

- docs-ref-services/iot-hub.md
> IoT - intro

- docs-ref-services/key-vault.md
> Key Vault - intros and headings

- docs-ref-services/machine-learning.md
> Machine Learning - intros and headings

- docs-ref-services/media-services.md
> Media Services - intros and headings

- docs-ref-services/notification-hubs.md
> Notification Hub - fixes

- docs-ref-services/sql.md
added intros and heading section fixes
> SQL - added intros and heading sections

- docs-ref-services/scheduler.md
added intros and heading section fixes
> Scheduler - added intros and heading section fixes

- docs-ref-services/search.md
> Search - added intros for heading sections

- docs-ref-services/service-fabric.md
> Service Fabric - added intros for heading sections

- docs-ref-services/service-map.md
> Service Map - added intros for heading sections

- docs-ref-services/site-recovery.md
> Recovery Services - added intros for heading sections

- docs-ref-conceptual/index.yml
#sign-off
as per @thedanfernandez and @TomArcher 
cc @timheuer
> Node.js Dev Center - udpated tile text and opening sentence

- docs-ref-services/appservice.md
> App Services - Modules

- docs-ref-services/authorization.md
> Authorization - intros and headings

- docs-ref-services/storage.md
Create management and client sections. Add container creation code in client sample. Add management example code
> Storage - Update storage.md

- docs-ref-services/cdn.md
> CDN - intros

- docs-ref-services/cognitive-services.md
> Cognitive Services - intros and headings

- docs-ref-services/container-registry.md
> Container Registry - code

- docs-ref-services/redis-cache.md
> Redis - fixes

- docs-ref-services/mysql.md
> MySQL - minor grammar

- docs-ref-services/postgresql.md
> Postgres - typos

- docs-ref-services/event-hub.md
Add management code sample and format according to standards.
> Event-hub - code sample

- docs-ref-services/mysql.md
Fix link to mysql library in overview section. Improve intros and headings
> MySQL - repo link

- docs-ref-services/iot-hub.md
> IoT Hub - promise

- docs-ref-services/search.md
> removed comment

- docs-ref-conceptual/index.yml
> landing page card - tools

- docs-ref-conceptual/index.yml
> landing page card - tools (#145)

- docs-ref-services/activedirectory.md
Fix code sample and add Client package header
> Active-directory - code samples and header

- docs-ref-conceptual/node-azure-tools.md
as per feedback from meeting with the review team and Scott, these are not steps, but rather optional things to install.
#sign-off
> made the steps "optional"

- docs-ref-services/billing.md
Fixed after discussion with PM's
- This API is preview and is superseding the Azure Commerce APIs.
- However the only feature it currently supports is invoices (hence light on descriptions) which has been taken from the Azure billing REST endpoint docs https://docs.microsoft.com/en-us/rest/api/billing/
- Spoke to John Lian <jlian@microsoft.com> and Joe Self <Joe.Self@microsoft.com> to confirm information.
> Azure Billing Service

- .openpublishing.redirection.json
redirects traffic from an outdated article to newer content on code.visualstudio.com
> redirect vscode content to code.visualstudio.com

- docs-ref-services/other.md
Hello, @cshoe,
Translator has reported possible source content issue. According to page https://docs.microsoft.com/es-es/nodejs/api/overview/azure/?view=azure-node-2.0.0, it might look like another Azure service, but we think it is a general term, based in this string: This module includes all of the individual Azure Node.js modules in a single place. 
Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR, or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
Many thanks in advance.
> M11126: Possible mistake in title

- docs-ref-conceptual/includes/virtualmachines-samples.md
- docs-ref-conceptual/node-samples-services-compute.md
- docs-ref-services/mysql.md
- docs-ref-services/virtualmachines.md
Some links have wrong URLs so I fixed these links.
> fix some links

- docs-ref-conceptual/index.yml
enable experiement on node developer center
> add experiment metadata to dev center page

- docs-ref-services/mysql.md
Removing rogue tags:
ms.prod: azure
ms.technology: azure
> Updating Metadata

- docs-ref-services/speech-service.md
@sudeepku  - please have a look.
> docs-ref-services/speech-service.md: initial version

- docs-ref-services/activedirectory.md
Updating metadata to remove ms.service based on this report: https://msit.powerbi.com/groups/me/reports/58580efe-c697-4e20-a7dd-88908d4af9ae/ReportSection64c0fd9156f2b8cc3fe8
> Updating metadata to remove ms.service

- docs-ref-conceptual/index.yml
Hello, @rloutlaw,
Translator has reported possible source content issue. 
Description: ""teams" seems to be unnecessary."
Please review and merge the suggested proposed file change to avoid this error. If you make related fix in another PR, then share your PR number, so we can confirm and close this PR.
Many thanks in advance.
> V31984: Removing possible extra word

- docs-ref-conceptual/index.yml
> Fix Issues #424

- docs-ref-conceptual/index.yml
> Rename VSTS to Azure DevOps Projects

- docs-ref-conceptual/index.yml
> Add GitHub Actions under DevOps section

- docs-ref-conceptual/index.yml
Fixed about #410 . Please review and approve it.
> Fixed links to pages about Messaging in getting started document

- docs-ref-services/backup.md
removing prod and technology as they are not valid metadata values
> removing prod and technology metadata

- docs-ref-conceptual/index.yml
Hello @rloutlaw,
Translator has reported possible source content issue.
Please review and merge the suggested proposed file change to avoid this error. If you make related fix in another PR, then share your PR number, so we can confirm and close this PR.
Many thanks in advance.
> M35917: Typo: "Chose"

- docs-ref-services/batch-ai.md
Adding a home page for Batch AI so we can put a banner explaining that Batch AI has been deprecated.
> Batch AI home page for deprecation banner

- docs-ref-services/mixed-reality.md
> Amend wrong title

- docs-ref-conceptual/index.yml
Fixing CATS report errors per https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1548994
> fixes for CATS report

- docs-ref-services/cognitive-services.md
- docs-ref-services/speech-service.md
made changes to metadata only removing ms.prod and ms.technology
> Metadata fix 20AUG19 ms.prod ms.tech remove

- preview-packages/docs-ref-mapping/reference.yml
@ramya-rao-a There is something else going on with what we're seeing on the site. What we see here: https://docs.microsoft.com/en-us/javascript/api/overview/azure/?view=azure-node-preview doesn't actually align with the current settings for the ToC. 
For instance `@azure/storage-file-share` is definitely present, but isn't reflected on the currently published ToC.
Regardless, the CI is updated to what we expect (latest preview), and I've organized the below as well. If there are additional updates necessary i'll make them.
> Update Preview Documentation ToC

- docs-ref-mapping/reference.yml
@chidozieononiwu I didn't catch this when I was skimming the review docs. Resolving it here.
> Resolve mis-named package

- docs-ref-mapping/reference.yml
- docs-ref-services/storage-blob-readme.md
- docs-ref-services/storage-fileshare-readme.md
- docs-ref-services/storage-index.md
- docs-ref-services/storage-overview.md
- docs-ref-services/storage-queue-readme.md
> Publish Storage Readme Updates to Live

- docs-ref-services/service-bus.md
Added two sections: management package and client package with links to documentation for the packages
> Added two sections: management package and client package

- docs-ref-autogen/azure-iothub/Client.yml
- docs-ref-autogen/azure-iothub/JobClient.yml
- docs-ref-autogen/azure-iothub/Registry.yml
Path IOT hub on Smoke-Test Branch
> Patch IOT hub

- docs-ref-services/activedirectory.md
Removed links to samples that have been archived as we don't want customers to use this anymore.
Fixes https://github.com/MicrosoftDocs/azure-docs-sdk-node/issues/772
> Updated the note to migrate to Microsoft Graph

- docs-ref-mapping/reference-unified.yml
Adding AnomalyDetector to reference-unified
> Anomalydetector ref mapping

- docs-ref-mapping/reference-unified.yml
These were added following, scbedd's instructions to prepare the Azure Communication Services reference documentation.
There will be one of these per language and this is the first so please feel free to let me know if there are any problems which may also be found in the other languages.
Thank you
> feat(acs): add Communication Toc entries

- previous-packages/docs-ref-mapping/reference.yml
> Legacy Mapping Update

- docs-ref-mapping/reference-unified.yml
- Updating reference docs index to add metrics advisor
> add metrics advisor service to reference index

- docs-ref-mapping/reference.yml
- preview-packages/docs-ref-mapping/reference.yml
For service-page docfx v3 migration.
> only '*' in Other

- docs-ref-services/service-bus.md
Between the two packages the client package is probably more likely to be the one that customers are trying to get to.
So this just swaps the position of the two (client on top, management package on bottom).
> [service-bus] Swapping mgmt and client links

- docs-ref-services/service-bus.md
Both of these are good resources for developers looking to get started with Service Bus in JavaScript.
> Update overview page to include a link readme link and TypeScript samples link

- docs-ref-services/latest/activedirectory.md
Now that we're able to edit the topic, cleaning up the note section and updating the topic to provide more actionable info. Addresses additional comment from https://github.com/MicrosoftDocs/azure-docs-sdk-node/issues/759
> Cleaning up outdated info and addressing GH issue

- docs-ref-services/latest/app-configuration-readme.md
- docs-ref-services/latest/eventhubs-checkpointstore-blob-readme.md
- docs-ref-services/latest/service-bus.md
- docs-ref-services/latest/storage-index.md
- docs-ref-services/legacy/app-configuration-readme.md
- docs-ref-services/legacy/eventhubs-checkpointstore-blob-readme.md
- docs-ref-services/legacy/storage-index.md
- docs-ref-services/preview/app-configuration-readme.md
- docs-ref-services/preview/digital-twins-readme.md
- docs-ref-services/preview/event-hubs-readme.md
- docs-ref-services/preview/eventhubs-checkpointstore-blob-readme.md
- docs-ref-services/preview/storage-index.md
Anyone notified by GitHub: this is for [user story 1812096](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1812096).
Addresses hard coded locales.
We are fixing issues related to Accessibility, SEO, and code blocks. You are welcome to review this PR, but for these changes, you don't need to sign off.
This is a bulk update.
Thanks -
> Message Fixes: User Story 1812096 - BULK

- docs-ref-services/latest/cosmos-db.md
The old link resolved to a page not found error,
new link here: https://docs.microsoft.com/en-us/samples/azure-samples/azure-cosmos-db-sql-api-nodejs-getting-started/azure-cosmos-db-sql-api-nodejs-getting-started/
> Update developing a js app link

- docs-ref-autogen/@azure/cosmos/Resource.yml
Excerpts taken from:
* https://docs.microsoft.com/en-us/rest/api/cosmos-db/documents
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet
> Fix incorrect information about document id

- docfx.json
Adds docs products taxonomy to the repo to improve findability experiences (onsite search, recommendations and others)
> add products taxonomy  to improve findability

- docs-ref-services/latest/appservice.md
Both of these repos have been archived - so maybe the better fix is to remove them @ramya-rao-a ?
> App Service - Fix links to samples

- docfx.json
Enables the scoped search feature to filter search results to Azure content
> Scope ref search to Azure content

- docs-ref-mapping/reference-unified.yml
- docs-ref-mapping/reference.yml
I honestly could swear I actually _checked_ this in the review, but I must have been confusing it with a different PR. This should resolve the 404s.
> Update Face-Readme Location

- docfx.json
- preview-packages/docs-ref-mapping/reference.yml
1. update mapping
2. add metadata
> Onboarding purview account

- docs-ref-mapping/reference-unified.yml
Add toc for a few newly released packages. 
Also to resolve this issue https://github.com/Azure/azure-sdk-for-js/issues/18815
> add-mapping-for-newly-released-packages

- docs-ref-mapping/reference-unified.yml
- Corrected the package name for @azure/logger in the toc - from this PR -https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/1322/files#diff-594596e7bb045eeccea024715d4bb660b147569f1de067a3ed9d27d7a8dc4992R1512
> fix the logger toc

- ci-configs/packages-latest.json
Docs CI has progressed past the point of failure -- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=279906&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102
> Pin @azure/communication-react to 1.0.0

- docfx.json
Addresses https://github.com/Azure/azure-sdk-for-net/issues/27450
> Update Azure SDK for JS product feedback link

- ci-configs/packages-latest.json
It's published to an independent repo
> Remove msal-node

- preview-packages/docs-ref-autogen/@azure/arm-securityinsight/McasDataConnector.yml
-------
cc: @VSC-Service-Account
> update product name

- docfx.json
Replace 1 instance of ms.service value = cdn with azure-cdn in 1 file.
> Bulk Metadata Update - cdn

- docfx.json
- docs-ref-services/latest/functions.md
Replace ms.service value = functions with azure-functions
> Bulk Metadata Update - functions

- docs-ref-services/latest/iot-hub.md
Updating some broken links reported in https://github.com/Azure/azure-sdk-for-js/issues/25477
> Fix broken links in iot-hub.md

- metadata/latest/azure-applicationinsights-query.json
- metadata/latest/azure-arm-sql.json
- metadata/latest/azure-communication-calling-effects.json
- metadata/latest/azure-communication-react.json
- metadata/latest/azure-communication-sms.json
- metadata/latest/azure-eventhubs-checkpointstore-blob.json
- metadata/preview/azure-ai-document-translator.json
- metadata/preview/azure-arm-cosmosdb.json
- metadata/preview/azure-communication-administration.json
- metadata/preview/azure-iot-device-update.json
- metadata/preview/azure-loganalytics.json
- metadata/preview/azure-quantum-jobs.json
- metadata/preview/azure-synapse-monitoring.json
This is part of the work to make the json files the source of truth which will allow partner teams to more easily onboard/service libraries that aren't released as part of the mono-repositories.
@danieljurek this are the files for Javascript that I'm updating. Missing files were added, some things (spring) that shouldn't be there were removed, etc.
> Add missing json, update versions that weren't correct

- metadata/latest/azure-functions.json
- metadata/preview/azure-functions.json
Here are links to the test pages. They look as-expected to me:
- preview: https://review.learn.microsoft.com/en-us/javascript/api/@azure/functions/?view=azure-node-preview&branch=erijiz%2Ftest-azurefunctions
- latest: https://review.learn.microsoft.com/en-us/javascript/api/@azure/functions/?view=azure-node-latest&branch=erijiz%2Ftest-azurefunctions
related to https://github.com/Azure/azure-sdk/pull/6577
> Add Azure Functions metadata json file

- docfx.json
A Pull Request has been made from the **Learn Platform's Metadata Management System**. Please review and merge this Pull Request within **5 days**. If you have any questions or concerns about the purpose of these metadata updates, please contact docs-allowlist-mgmt@microsoft.com. If you are not the correct contact for this content and repository, please notify Metadata-Management@microsoft.com. 
If this Pull Request is not merged within **14 days**, it will be automatically merged by our system to ensure the timeliness of the metadata update. **This includes bypassing the Repository's Branch Policy, including if Review Required is enabled**. Please notify Metadata-Management@microsoft.com if you have questions or concerns or would like Pull Requests for metadata updates to merge …
> [METADATA UPDATE][Merge by 2024-08-13] Global ms.service and ms.subservice metadata update

- metadata/latest/azure-communication-react.json
Update @azure/communication-react to latest GA 1.27.0
> Update @azure/communication-react to latest GA 1.27.0
